

# Plants
PEA_SHOOTER_DAMAGE = 5
SNOW_PEA_SHOOTER_DAMAGE = 8
SUN_FLOWER_DAMAGE = 0
SIB_ZAMINI_DAMAGE = 0

PEA_SHOOTER_HEALTH = 40
SNOW_PEA_SHOOTER_HEALTH = 30
SUN_FLOWER_HEALTHE = 30
SIB_ZAMINI_HEALTH = 200

PEA_SHOOTER_COOL_DOWN = 5
SNOW_PEA_SHOOTER_COOL_DOWN = 9
SUN_FLOWER_COOL_DOWN = 10
SIB_ZAMINI_COOL_DOWN = 10

PEA_SHOOTER_HIT_RATE = 5
SNOW_PEA_SHOOTER_HIT_RATE = 5
SUN_FLOWER_HIT_RATE = 12
SIB_ZAMINI_HIT_RATE = 0

PEA_SHOOTER_SPEED = 7
SNOW_PEA_SHOOTER_SPEED = 5
SUN_FLOWER_SPEED = 0
SIB_ZAMINI_SPEED = 0

PEA_SHOOTER_PRICE = 4
SNOW_PEA_SHOOTER_PRICE = 6
SUN_FLOWER_PRICE = 2
SIB_ZAMINI_PRICE = 2



# Zombies
REGULAR_ZOMBIE_DAMAGE = 10
GIANT_ZOMBIE_DAMAGE = 20

REGULAR_ZOMBIE_HEALTH = 50
GIANT_ZOMBIE_HEALTH = 80

REGULAR_ZOMBIE_HIT_RATE = 5
GIANT_ZOMBIE_HIT_RATE = 6

REGULAR_ZOMBIE_SPEED = 7
GIANT_ZOMBIE_SPEED = 5



# OtherItems
SPEED = 10
INTERVAL = 10
