import json

# Open the JSON file
with open("consts.json", "r") as file:
    # Load the JSON data
    salam = json.load(file)

# Access a value from the JSON data
# print(salam["mahdy"])



# Plants
PEA_SHOOTER_DAMAGE = 5
SNOW_PEA_SHOOTER_DAMAGE = 8
SUN_FLOWER_DAMAGE = 0
SIB_ZAMINI_DAMAGE = 0

PEA_SHOOTER_HEALTH = 40
SNOW_PEA_SHOOTER_HEALTH = 30
SUN_FLOWER_HEALTH = 30
SIB_ZAMINI_HEALTH = 200

PEA_SHOOTER_COOL_DOWN = 5
SNOW_PEA_SHOOTER_COOL_DOWN = 9
SUN_FLOWER_COOL_DOWN = 10
SIB_ZAMINI_COOL_DOWN = 10

PEA_SHOOTER_HIT_RATE = 5
SNOW_PEA_SHOOTER_HIT_RATE = 5
SUN_FLOWER_HIT_RATE = 12
SIB_ZAMINI_HIT_RATE = 0

PEA_SHOOTER_SPEED = 7
SNOW_PEA_SHOOTER_SPEED = 5
SUN_FLOWER_SPEED = 0
SIB_ZAMINI_SPEED = 0

PEA_SHOOTER_PRICE = 4
SNOW_PEA_SHOOTER_PRICE = 6
SUN_FLOWER_PRICE = 2
SIB_ZAMINI_PRICE = 2



# Zombies
REGULAR_ZOMBIE_DAMAGE = 10
GIANT_ZOMBIE_DAMAGE = 20

REGULAR_ZOMBIE_HEALTH = 50
GIANT_ZOMBIE_HEALTH = 80

REGULAR_ZOMBIE_HIT_RATE = 5
GIANT_ZOMBIE_HIT_RATE = 6

REGULAR_ZOMBIE_SPEED = 7
GIANT_ZOMBIE_SPEED = 5



# OtherItems
SUN_SPEED = 10
SUN_INTERVAL = 10


# scale
SCALE = 1

# dict row -> y_pos
DICT_ROW_Y_POS = {
    0: 155,
    1: 265,
    2: 375,
    3: 485,
    4: 595
}

# dict row -> y_pos
DICT_Y_POS_ROW = {
    155: 0,
    265: 1,
    375: 2,
    485: 3,
    595: 4
}

# game time (sc)
GAME_TIME_IN_SEC = 100